vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        gallery_images:
            uri_prefix: '%app.path.gallery_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.gallery_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
